import { Grade, GradeTopic } from '@/types';

// 고1·고2·고3 × 5과목(math/physics/chemistry/biology/ethics) × 10개(1학기5+2학기5) = 150개 주제
export const GRADE_TOPICS: Record<Grade, Record<string, GradeTopic[]>> = {
  grade1: {
    math: [
      { semester: 'sem1', topic: '황금비와 자연·건축의 수학적 패턴 — 피보나치 수열·황금비 실측 분석', career: '건축학과·수학교육학과' },
      { semester: 'sem1', topic: '이차방정식으로 해석하는 포물선 운동 — 스마트폰 촬영과 회귀 피팅', career: '물리학과·스포츠공학' },
      { semester: 'sem1', topic: '불평등 분포와 부등식 — OECD 데이터로 로렌츠 곡선과 지니계수 분석', career: '경제학과·사회학과' },
      { semester: 'sem1', topic: '다항식 전개와 RSA 암호화 원리 — 수학으로 보는 정보보안 입문', career: '컴퓨터공학·정보보안학과' },
      { semester: 'sem1', topic: '스마트폰 화면 해상도와 비율의 수학 — PPI와 피타고라스 실측', career: '전자공학·UX디자인' },
      { semester: 'sem2', topic: '기후 데이터로 배우는 선형 회귀 — 서울 10년 기온 추세 분석', career: '환경공학·기상학' },
      { semester: 'sem2', topic: '로그함수로 이해하는 AI 손실 함수 — Cross-Entropy의 수학적 유도', career: 'AI공학·컴퓨터공학' },
      { semester: 'sem2', topic: '등비수열과 복리의 힘 — 20년 노후 자산 시뮬레이션', career: '경영학·금융공학' },
      { semester: 'sem2', topic: '확률과 베이즈 정리로 분석하는 추천 알고리즘 원리', career: '데이터과학·컴퓨터공학' },
      { semester: 'sem2', topic: '통계로 보는 입시 공정성 — 표준점수·Z-점수 비판적 분석', career: '통계학·교육학' },
    ],
    physics: [
      { semester: 'sem1', topic: '스마트폰 센서로 중력가속도 측정 — PhyPhox 앱 활용 오차 분석', career: '물리학·계측공학' },
      { semester: 'sem1', topic: '다양한 재질의 마찰계수 비교 실험 — 운동 마찰과 정지 마찰 정밀 측정', career: '재료공학·기계공학' },
      { semester: 'sem1', topic: '자전거 기어 변속과 에너지 효율 — 일-에너지 정리 실험 설계', career: '기계공학·스포츠과학' },
      { semester: 'sem1', topic: '소리 속도와 도플러 효과 — 신호 처리로 주파수 변화 실측', career: '음향공학·물리학' },
      { semester: 'sem1', topic: '투석기 발사각 최적화 — 포물선 운동으로 최대 사거리 분석', career: '항공우주공학·물리학' },
      { semester: 'sem2', topic: '태양광 패널 각도별 효율 측정 — 시간대·계절별 데이터 수집', career: '신재생에너지공학' },
      { semester: 'sem2', topic: '전자기 유도 코일 수 변화와 기전력 — 패러데이 법칙 검증', career: '전기공학·에너지공학' },
      { semester: 'sem2', topic: '노이즈 캔슬링 이어폰의 파동 간섭 원리 분석', career: '음향공학·전자공학' },
      { semester: 'sem2', topic: '표면 색과 열복사 흡수율 관계 — 스테판-볼츠만 측정', career: '열공학·건축환경공학' },
      { semester: 'sem2', topic: '지진파 P파·S파 도달 시간 차이로 진원 위치 추정', career: '지구물리학·지진공학' },
    ],
    chemistry: [
      { semester: 'sem1', topic: '음료수 속 구연산 함량 — 산염기 적정으로 농도·온도별 측정', career: '식품화학·약학' },
      { semester: 'sem1', topic: '불꽃반응 발광 파장 분석 — 분광계로 금속 이온 식별', career: '물리화학·재료공학' },
      { semester: 'sem1', topic: '비누 제조와 계면활성제 — 세정력 조건별 비교 측정', career: '화장품공학·화학공학' },
      { semester: 'sem1', topic: '양배추 지시약으로 pH 척도 제작 — 자연 지시약 활용 탐구', career: '화학교육·환경과학' },
      { semester: 'sem1', topic: '이온·공유·금속 결합 물성 비교 — 녹는점과 전도도 실험', career: '재료공학·화학' },
      { semester: 'sem2', topic: '철 부식 속도 환경 변수 실험 — 습도·염도·pH 조건 비교', career: '재료공학·환경공학' },
      { semester: 'sem2', topic: '광합성 색소 크로마토그래피 — Rf 값 측정과 엽록소 비교', career: '생화학·식물학' },
      { semester: 'sem2', topic: 'UV·미생물 조건별 플라스틱 분해 속도 비교 실험', career: '환경화학·고분자공학' },
      { semester: 'sem2', topic: '물 전기분해 수소 발생량 — 전류·전압 변수별 정량 측정', career: '수소에너지공학·화학공학' },
      { semester: 'sem2', topic: '아스피린 합성과 FeCl₃ 순도 검증 — 재결정으로 불순물 제거', career: '제약학·유기화학' },
    ],
    biology: [
      { semester: 'sem1', topic: '양파 세포 삼투압 현미경 측정 — 수크로스 농도별 등장점 결정', career: '세포생물학·의학' },
      { semester: 'sem1', topic: 'ABO 혈액형 유전 시뮬레이션 — 멘델 법칙 데이터 검증', career: '유전학·의학' },
      { semester: 'sem1', topic: '카탈레이스 온도별 활성 측정 — 기포 발생률 데이터 정량화', career: '생화학·의학' },
      { semester: 'sem1', topic: '효모 발효 CO₂ 발생 조건 탐구 — 온도·당 농도 최적화', career: '발효공학·식품생물학' },
      { semester: 'sem1', topic: '항생제 디스크 확산법 — 억제 직경 측정으로 효능 비교', career: '미생물학·의학' },
      { semester: 'sem2', topic: 'CRISPR-Cas9 원리와 윤리 — 유전자 가위 메커니즘 문헌 탐구', career: '유전공학·생명윤리' },
      { semester: 'sem2', topic: '미세플라스틱이 식물 생장에 미치는 영향 — 발아율·엽록소 측정', career: '환경생태학·농학' },
      { semester: 'sem2', topic: '암 세포 분열 이상 탐구 — 정상 vs 암세포 분열 주기 비교', career: '종양학·의학' },
      { semester: 'sem2', topic: '장내 미생물과 프로바이오틱스 — 식이별 균총 변화 분석', career: '장내미생물학·약학' },
      { semester: 'sem2', topic: '탄소 순환과 CO₂ 농도별 광합성 속도 측정 실험', career: '환경과학·식물생리학' },
    ],
    ethics: [
      { semester: 'sem1', topic: 'AI 판사 알고리즘 편향 — 공정성 이론과 실제 판결 데이터 분석', career: '법학·AI윤리학' },
      { semester: 'sem1', topic: 'SNS 혐오 표현과 표현의 자유 — 밀의 해악 원리 적용', career: '언론학·법학' },
      { semester: 'sem1', topic: '채식주의와 동물권 윤리 — 피터 싱어의 동물해방론 탐구', career: '철학·생명윤리' },
      { semester: 'sem1', topic: '기후 정의와 탄소 책임 분배 — 롤스 정의론 적용', career: '환경정책·철학' },
      { semester: 'sem1', topic: '뇌사와 존엄사 — 생명의 정의에 관한 칸트 vs 공리주의 비교', career: '의료윤리·법학' },
      { semester: 'sem2', topic: '딥페이크와 정보 윤리 — 허위정보 피해 사례와 책임 주체 분석', career: '정보윤리학·법학' },
      { semester: 'sem2', topic: '플랫폼 노동자 권리 — 긱이코노미 노동권 사각지대 탐구', career: '사회학·경제학·법학' },
      { semester: 'sem2', topic: '드론 전쟁의 정당성 — 정전론(Just War Theory) 적용 분석', career: '국제관계·철학' },
      { semester: 'sem2', topic: '사형제 응보론 vs 회복적 정의 — 국가별 범죄율 데이터 비교', career: '형사정책·법철학' },
      { semester: 'sem2', topic: 'AI 창작물 저작권 — 창작 주체성과 지식재산권의 충돌 탐구', career: '저작권법·AI정책' },
    ],
  },

  grade2: {
    math: [
      { semester: 'sem1', topic: '로지스틱 성장 모델로 감염병 확산 분석 — 코로나19 데이터 피팅과 R0 도출', career: '수리통계학·의대·보건정책' },
      { semester: 'sem1', topic: '몬테카를로 시뮬레이션으로 원주율 추정 — 난수·기댓값 이론과 수렴 속도 분석', career: '통계학·데이터사이언스·금융공학' },
      { semester: 'sem1', topic: '베지에 곡선의 수학 — 매개변수 방정식과 애니메이션 미분기하학', career: '컴퓨터그래픽스·소프트웨어공학' },
      { semester: 'sem1', topic: '선형계획법으로 물류 네트워크 최적화 — 심플렉스법 적용 비용 절감 계산', career: '산업공학·경영과학·물류학' },
      { semester: 'sem1', topic: '푸리에 급수로 분해하는 음악의 수학 — 악기 파형 데이터로 배음 구조 분석', career: '음향공학·신호처리·수학' },
      { semester: 'sem2', topic: 'AI 추천 시스템의 수학적 편향 비판 — SVD 분해로 협업 필터링 원인 분석', career: 'AI/ML공학·데이터윤리·통계학' },
      { semester: 'sem2', topic: '기후 예측 모델의 카오스 불확실성 — 로렌츠 방정식과 민감도 정량화', career: '기상학·환경공학·응용수학' },
      { semester: 'sem2', topic: '암호화폐는 랜덤워크인가 — 비트코인 수익률로 효율적 시장 가설 검증', career: '금융공학·계량경제학' },
      { semester: 'sem2', topic: '소수 분포의 비밀 — π(x)와 자연로그 근사 오차로 리만 가설 탐구', career: '순수수학·정수론·암호학' },
      { semester: 'sem2', topic: '투표 시스템의 수학적 불가능성 — 애로의 불가능성 정리 현실 사례 분석', career: '사회선택이론·정치학·경제수학' },
    ],
    physics: [
      { semester: 'sem1', topic: '초전도체 마이스너 효과 측정 — YBCO 액체질소 부상 높이와 임계온도 분석', career: '응집물질물리학·재료공학' },
      { semester: 'sem1', topic: '스마트폰 가속도계로 단순조화운동 분석 — PhyPhox로 용수철 상수 정밀 결정', career: '물리학·계측공학' },
      { semester: 'sem1', topic: '빛의 편광과 말뤼스 법칙 검증 — 편광판·광센서로 I=I₀cos²θ 실험', career: '광학공학·디스플레이공학' },
      { semester: 'sem1', topic: '유체 점성 측정 — 스토크스 법칙 적용으로 글리세린 점도 온도 의존성', career: '유체역학·화학공학·바이오의공학' },
      { semester: 'sem1', topic: 'LED 역전압법으로 플랑크 상수 결정 — 파장별 정지 전위로 양자역학 실험 재현', career: '양자물리학·반도체공학' },
      { semester: 'sem2', topic: '핵융합 에너지의 물리 — ITER 토카막 Q값 한계의 물리적 원인 비판 분석', career: '핵융합공학·플라즈마물리학' },
      { semester: 'sem2', topic: '중력파 검출 LIGO 마이컬슨 간섭계 원리 재구성 — 민감도 스펙트럼 분석', career: '천체물리학·정밀계측' },
      { semester: 'sem2', topic: '전기차 배터리 열폭주 — 열역학 제1·2법칙으로 체인반응 메커니즘 분석', career: '에너지공학·전기차공학' },
      { semester: 'sem2', topic: '온도·습도 변수 통제 음속 측정 — Newton-Laplace 공식과 이상기체 한계 규명', career: '음향공학·기상학·응용물리학' },
      { semester: 'sem2', topic: '태양광 패널 효율의 물리적 한계 — Shockley-Queisser 한계(~33%) vs 실제 데이터', career: '태양광공학·반도체물리학' },
    ],
    chemistry: [
      { semester: 'sem1', topic: '카페인 추출 효율 비교 — 용매 극성과 분배 계수(Kd) TLC 측정', career: '유기화학·제약화학·식품공학' },
      { semester: 'sem1', topic: '광촉매 TiO₂ 메틸렌블루 분해 속도론 — UV 조사 시간별 반응 속도 상수 k 결정', career: '환경화학·촉매공학·화학공학' },
      { semester: 'sem1', topic: 'Henderson-Hasselbalch 완충 용액 검증 — pH 변화로 완충 능력 정량 측정', career: '생화학·의약학·화학교육' },
      { semester: 'sem1', topic: '전기화학적 구리 전착 — 전류·시간·면적 변수로 패러데이 법칙 비례 상수 결정', career: '전기화학·재료공학' },
      { semester: 'sem1', topic: '향수 분자의 증기압 측정 — 클라우지우스-클라페이론 방정식으로 증발 엔탈피 결정', career: '향료화학·물리화학' },
      { semester: 'sem2', topic: '미세플라스틱의 중금속 농집 — 납·카드뮴 흡착 실험과 먹이사슬 경로 비판 분석', career: '환경화학·독성학·해양환경학' },
      { semester: 'sem2', topic: '리튬이온 배터리 전해질 — 고체 vs 액체 이온 전도도 비교와 상용화 장벽 분석', career: '배터리화학·재료화학' },
      { semester: 'sem2', topic: '가정용 세제 계면활성제 CMC 결정 — 표면장력 측정과 환경친화 세제 설계', career: '화장품화학·계면화학·환경공학' },
      { semester: 'sem2', topic: '자동차 연소 NOx 생성 화학 — 젤도비치 메커니즘과 SCR 탈질 효율 비판 평가', career: '대기화학·자동차공학·환경화학' },
      { semester: 'sem2', topic: '아스피린 합성과 HPLC 순도 검증 — GMP 기준과 현실 데이터 비교', career: '제약학·유기화학·의약화학' },
    ],
    biology: [
      { semester: 'sem1', topic: 'CRISPR sgRNA 설계와 표적 특이성 분석 — Benchling으로 off-target 예측 점수 분석', career: '분자생물학·유전공학·의학' },
      { semester: 'sem1', topic: '효모 발효 3요인 실험 설계 — 온도·pH·당 농도 최적화로 CO₂ 정량화', career: '발효공학·식품생물학·생명공학' },
      { semester: 'sem1', topic: '수생식물 광보상점 결정 — Elodea 기포 계수법으로 C3/C4 식물 비교', career: '식물생리학·농업과학·생태학' },
      { semester: 'sem1', topic: '피부 마이크로바이옴 세균 배양 비교 — 세척 전후·세정제별 CFU 정량 분석', career: '미생물학·공중보건학·의학' },
      { semester: 'sem1', topic: '감자 디스크 삼투 퍼텐셜 계산 — 0~1.0M 수크로스 침지로 등장 농도 결정', career: '세포생물학·식물학·의생명과학' },
      { semester: 'sem2', topic: '항생제 내성균 진화유전학 비판 — 수평 유전자 이동과 내성균 출현율 상관관계', career: '미생물학·감염병학·의학' },
      { semester: 'sem2', topic: '장내 미생물과 뇌-장 축 분석 — 미주신경·세로토닌 경로와 우울증 상관관계', career: '신경과학·정신의학·장내미생물학' },
      { semester: 'sem2', topic: 'GMO 콩 글리포세이트 내성 생태계 영향 — EPSPS 돌연변이와 내성 잡초 확산 비판', career: '분자유전학·농업생물공학·환경생태학' },
      { semester: 'sem2', topic: '텔로미어 단축과 세포 노화 — 헤이플릭 한계와 암세포 텔로머라제 과발현 분석', career: '노화의학·종양학·세포생물학' },
      { semester: 'sem2', topic: '장기강화(LTP)와 최적 학습 신경생물학 — AMPA/NMDA 수용체와 학습 간격 근거', career: '신경과학·인지과학·의학' },
    ],
    ethics: [
      { semester: 'sem1', topic: 'AI 판사 공정성 — COMPAS 재범 예측 알고리즘의 인종 편향 데이터 분석', career: '법학·AI윤리학·정치철학' },
      { semester: 'sem1', topic: '공장식 축산의 윤리 — 피터 싱어 이익평등 원칙 vs 칸트 의무론 비교', career: '생명윤리학·철학·동물복지학' },
      { semester: 'sem1', topic: '기후 정의와 세대 간 윤리 — 롤스 정의론으로 탄소 예산 세대 간 배분 탐구', career: '환경윤리학·정책학·정치철학' },
      { semester: 'sem1', topic: '디지털 감시와 팬옵티콘 — 벤담의 통제 원리를 현대 빅데이터 감시에 적용', career: '법철학·정보윤리학·사회학' },
      { semester: 'sem1', topic: '뇌사와 장기 이식 — 옵트아웃 추정동의제의 자율성 윤리 vs 공리주의', career: '의료윤리학·법학·사회복지학' },
      { semester: 'sem2', topic: '메타버스 아바타의 도덕적 지위 — 실존주의·사회계약론으로 제도적 대안 제시', career: '디지털윤리학·법학·철학' },
      { semester: 'sem2', topic: '자율주행차의 트롤리 딜레마 — MIT 도덕 기계 210개국 데이터 비판 분석', career: 'AI윤리학·자동차공학정책·철학' },
      { semester: 'sem2', topic: 'SNS 혐오 표현과 플랫폼 윤리 책임 — 밀의 해악 원리와 롤스 공정성 기준 적용', career: '미디어윤리학·법학·사회학' },
      { semester: 'sem2', topic: 'BCI 기술과 인지 불평등 — 샌델의 완전주의 비판과 접근성 정책 대안 탐구', career: '생명윤리학·철학·의공학정책' },
      { semester: 'sem2', topic: '사형제 폐지 논쟁 — 국가별 살인 범죄율 데이터로 응보적 vs 회복적 정의 비교', career: '형사정책학·법철학·사회학' },
    ],
  },

  grade3: {
    math: [
      { semester: 'sem1', topic: '베이즈 정리와 의료 진단 정확도 분석 — NHIS 데이터로 위양성 오류율 정량화', career: '의대·보건의료정보학' },
      { semester: 'sem1', topic: '미분방정식 SIR 모델로 전염병 확산 검증 — scipy 수치해와 실제 데이터 RMSE 계산', career: '수리생물학·통계학·공중보건' },
      { semester: 'sem1', topic: '프랙탈 차원과 자연의 자기유사성 — ImageJ로 해안선·혈관 하우스도르프 차원 측정', career: '수학과·물리학과·생명과학' },
      { semester: 'sem1', topic: 'RSA 암호와 소수 분포의 수학 — 파이썬 소인수분해 시간 측정으로 안전성 분석', career: '컴퓨터공학·수학과·사이버보안' },
      { semester: 'sem1', topic: '게임이론과 내쉬 균형 — 전기차 시장 경쟁 보수 행렬 직접 설계와 균형점 계산', career: '경제학·경영학·수학과' },
      { semester: 'sem2', topic: '위상수학 입문 — 뫼비우스 띠·클라인 병의 오일러 지표와 위상 불변량 탐구', career: '수학과·물리학과' },
      { semester: 'sem2', topic: '경사하강법과 머신러닝의 수학적 기반 — 다변수 극값 문제와 신경망 학습 연결', career: 'AI학과·컴퓨터공학·통계학' },
      { semester: 'sem2', topic: '로지스틱 맵으로 탐구하는 카오스 이론 — 파이썬 분기 다이어그램과 리아푸노프 지수', career: '수학과·물리학과·복잡계과학' },
      { semester: 'sem2', topic: '타원곡선 암호 ECC와 암호화폐 서명 원리 — 군 구조와 ECDSA 수학적 기초 탐구', career: '수학과·컴퓨터공학·핀테크' },
      { semester: 'sem2', topic: '복소함수와 줄리아 집합 — 만델브로트 집합의 수학적 구조와 자기유사성 시각화', career: '순수수학·컴퓨터과학' },
    ],
    physics: [
      { semester: 'sem1', topic: '초전도체 마이스너 효과와 자속 양자화 — LK-99 논란 비교 분석', career: '물리학과·재료공학·에너지공학' },
      { semester: 'sem1', topic: '핵융합 ITER·NIF 로손 기준 검증 — 2024년 NIF 점화 데이터 활용', career: '핵공학·물리학과·에너지공학' },
      { semester: 'sem1', topic: '양자 얽힘과 벨 부등식 — 2022년 노벨 물리학상 CHSH 수학적 유도와 국소성 한계 증명', career: '물리학과·양자정보과학' },
      { semester: 'sem1', topic: '특수 상대성 이론과 GPS 시간 보정 정량화 — 위성 시간 팽창 38μs/일 계산', career: '물리학과·항공우주공학·천문학' },
      { semester: 'sem1', topic: '제베크 효과와 열전 소자 — 온도차-전압 선형성 측정과 포논-전자 결합 분석', career: '물리학과·신소재공학·에너지공학' },
      { semester: 'sem2', topic: '중력파 검출 LIGO 마이컬슨 간섭계 분석 — 공명 주파수 계산과 민감도 스펙트럼', career: '물리학과·천문학·정밀계측공학' },
      { semester: 'sem2', topic: '위상 절연체와 양자 홀 효과 — 2016년 노벨상 연계 베리 위상 도식화', career: '물리학과·재료공학·반도체공학' },
      { semester: 'sem2', topic: '로렌츠 어트랙터 룽게-쿠타 수치 시뮬레이션 — 파이썬 3D 어트랙터 시각화', career: '물리학과·기상학·복잡계과학' },
      { semester: 'sem2', topic: '광전 효과로 플랑크 상수 측정 — LED 파장별 선형 회귀와 태양전지 연계', career: '물리학과·광공학·신소재공학' },
      { semester: 'sem2', topic: '표면 장력과 모세관 창발 현상 — 다양한 액체 비교와 코사인 법칙 검증', career: '물리학과·화학과·생명과학부' },
    ],
    chemistry: [
      { semester: 'sem1', topic: '리튬이온 배터리 열화 EIS 내부저항 분석 — 2024년 전고체 배터리와 용량 감소 비교', career: '화학공학·재료공학·에너지공학' },
      { semester: 'sem1', topic: '약물 키랄성 — 탈리도마이드 R/S 배열 편광계 실험과 수용체 선택성 FDA 기준 분석', career: '약학과·의대·화학과' },
      { semester: 'sem1', topic: '촉매 vs 효소 — H₂O₂ 분해 온도별 아레니우스 플롯으로 활성화 에너지 비교', career: '화학과·생화학·약학' },
      { semester: 'sem1', topic: '탄소 포집 — 아민 흡수제와 MOF 메커니즘 비교로 CO₂ 흡수량 정량화', career: '화학공학·환경공학·에너지공학' },
      { semester: 'sem1', topic: '계면활성제 CMC 측정과 세정 메커니즘 — 온도 의존성 비교 분석', career: '화학과·화장품공학·제약공학' },
      { semester: 'sem2', topic: 'CRISPR-Cas9 DNA 절단의 원자 수준 화학 — HNH·RuvC 도메인 2020년 노벨상 연계', career: '생화학·분자생물학·의대' },
      { semester: 'sem2', topic: '전기화학적 질소 고정 — 하버-보슈 대안 탐구와 패러데이 효율 계산', career: '화학공학·환경화학·농학' },
      { semester: 'sem2', topic: 'PLA 합성 원리와 조건별 생분해 속도 측정 — pH·온도·미생물 질량 감소율 실험', career: '고분자공학·환경공학·화학과' },
      { semester: 'sem2', topic: '반도체 도핑 화학 — 밴드 이론과 전도도 변화로 캐리어 농도 추정', career: '반도체공학·재료공학·전자공학' },
      { semester: 'sem2', topic: 'HPLC로 아스피린 순도 측정 — 표준곡선·LOD 계산과 역상 HPLC 원리 분석', career: '약학과·분석화학·의대' },
    ],
    biology: [
      { semester: 'sem1', topic: '후성유전학 — DNA 메틸화와 환경 의존적 유전자 발현 일란성 쌍둥이 사례 분석', career: '의대·생명과학·유전공학' },
      { semester: 'sem1', topic: '장내 마이크로바이옴과 뇌-장 축(Gut-Brain Axis) — 세로토닌·GABA 합성 메커니즘', career: '의대·약학·생명과학' },
      { semester: 'sem1', topic: 'CRISPR+겸상적혈구 — Casgevy FDA 승인(2023) 원리와 BCL11A 편집 메커니즘', career: '의대·분자생물학·생명공학' },
      { semester: 'sem1', topic: '텔로미어 단축과 세포 노화 — 텔로머라제 활성과 암세포 불사 형질 비교', career: '의대·생화학·노인의학' },
      { semester: 'sem1', topic: 'C3/C4/CAM 식물 광합성 효율 비교 — 옥수수 vs 시금치 광포화점 측정', career: '농생명공학·식물생물학·환경과학' },
      { semester: 'sem2', topic: '단일세포 RNA 시퀀싱(scRNA-seq) — 공개 데이터셋 t-SNE/UMAP 시각화 탐구', career: '의대·생명과학·바이오인포매틱스' },
      { semester: 'sem2', topic: 'CAR-T 세포 치료 설계 원리와 고형암 한계 — 2025년 차세대 CAR-NK 동향 분석', career: '의대·면역학·생명공학' },
      { semester: 'sem2', topic: '뉴로플라스티시티 — LTP/LTD와 BDNF로 반복 학습 전후 기억 과제 성능 측정', career: '의대·신경과학·심리학' },
      { semester: 'sem2', topic: '이타적 행동의 진화 — 해밀턴 규칙과 팃포탯 전략 전략별 생존율 시뮬레이션', career: '진화생물학·생태학·심리학' },
      { semester: 'sem2', topic: '합성생물학 — JCVI-syn3.0 최소 세포 53개 필수 유전자 기능 분류 탐구', career: '생명공학·의대·철학과' },
    ],
    ethics: [
      { semester: 'sem1', topic: 'AI 도덕 행위자성 — ChatGPT는 도덕 주체가 될 수 있는가 직접 실험 귀납 분석', career: '철학·법학·AI윤리' },
      { semester: 'sem1', topic: '디자이너 베이비 — 허젠쿠이 사건부터 2024년 모라토리엄까지 3가지 윤리 이론 적용', career: '의대·철학·생명윤리' },
      { semester: 'sem1', topic: '기후 정의 — 롤스의 무지의 베일로 국가별 탄소 예산 공정 배분 원칙 도출', career: '환경정책·철학·법학·국제관계' },
      { semester: 'sem1', topic: '안락사와 존엄사 — 네덜란드·캐나다 MAiD vs 한국 법제 경사면 논증 검토', career: '의대·법학·철학' },
      { semester: 'sem1', topic: '필터버블과 민주주의 — 다른 성향 계정으로 알고리즘 비교 실험과 하버마스 공론장 분석', career: '사회학·언론정보학·철학' },
      { semester: 'sem2', topic: '데이터 주권 — GDPR 잊혀질 권리와 개인정보보호법(2024) 앱 수집 항목 직접 조사', career: '법학·IT정책·철학' },
      { semester: 'sem2', topic: '리벳 실험과 자유의지 — 신경결정론과 도덕 책임 반응 시간 측정 재현 시도', career: '철학·신경과학·법학' },
      { semester: 'sem2', topic: '동물 실험 3R 원칙의 한계 — 오가노이드·AI 대체 기술과 국내 승인 추이 데이터 분석', career: '수의학·약학·생명윤리' },
      { semester: 'sem2', topic: '공정 무역의 역설 — 피터 싱어 vs 무우야 노코 공정무역 농가 소득 실증 비교', career: '국제개발·경제학·철학' },
      { semester: 'sem2', topic: '트랜스휴머니즘 — Neuralink 2025년 임상 사례와 치료 vs 향상의 존엄성 경계 설정', career: '의대·철학·생명공학' },
    ],
  },
};

export function getGradeTopics(grade: Grade, subjectId: string): GradeTopic[] {
  return GRADE_TOPICS[grade]?.[subjectId] ?? [];
}
